# Generated by Django 4.2.30 on 2026-10-06 02:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tblcs_academic_year',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('risk_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DISMISSED', 'Dismissed'), ('CONFIRMED', 'Confirmed'), ('EXCUSED', 'Excused')], default='OPEN', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblcs_anomaly_flag',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=40)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('grace_minutes', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classes', to='core.academicyear')),
            ],
            options={
                'db_table': 'tblcs_class',
                'ordering': ['class_code'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=9)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_closed', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblcs_class_session',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tblcs_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=7)),
                ('year_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('approval_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=8, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_consent_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_notice_version', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('qr_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='profiles', to='core.department')),
            ],
            options={
                'db_table': 'tblcs_profile',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tblcs_subject',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StampAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('QR', 'QR Scan'), ('CODE', 'Code')], max_length=4)),
                ('outcome', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('INVALID', 'Invalid'), ('EXPIRED', 'Expired'), ('DUPLICATE', 'Duplicate'), ('INELIGIBLE', 'Ineligible'), ('SESSION_CLOSED', 'Session Closed')], max_length=14)),
                ('token_bucket', models.BigIntegerField(blank=True, null=True)),
                ('token_age_s', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamp_attempts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamp_attempts', to='core.classsession')),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamp_attempts', to='core.profile')),
            ],
            options={
                'db_table': 'tblcs_stamp_attempt',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('DISMISS', 'Dismiss'), ('CONFIRM_PROXY', 'Confirm Proxy'), ('EXCUSE', 'Excuse'), ('OTHER', 'Other')], max_length=14)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_flag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='review_actions', to='core.anomalyflag')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='review_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblcs_review_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('years_total', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='programs', to='core.department')),
            ],
            options={
                'db_table': 'tblcs_program',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='profiles', to='core.program'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classstamp_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], validators=[django.core.validators.MaxValueValidator(6)])),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('room', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.RESTRICT, related_name='slots', to='core.class')),
            ],
            options={
                'db_table': 'tblcs_class_slot',
                'unique_together': {('class_obj', 'weekday', 'starts_at')},
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='core.classslot'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classes', to='core.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='taught_classes', to='core.profile'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblcs_audit_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], max_length=8)),
                ('method', models.CharField(choices=[('QR', 'QR Scan'), ('CODE', 'Code'), ('MANUAL', 'Manual'), ('SYSTEM', 'System')], max_length=6)),
                ('stamped_at', models.DateTimeField(blank=True, null=True)),
                ('late_minutes', models.PositiveSmallIntegerField(default=0)),
                ('correction_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='marked_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_records', to='core.classsession')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_records', to='core.profile')),
            ],
            options={
                'db_table': 'tblcs_attendance_record',
                'unique_together': {('session', 'student_profile')},
            },
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='anomaly_flags', to='core.attendancerecord'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=9)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='core.class')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='core.profile')),
            ],
            options={
                'db_table': 'tblcs_enrollment',
                'unique_together': {('student_profile', 'class_obj')},
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='curriculum_entries', to='core.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='curriculum_entries', to='core.subject')),
            ],
            options={
                'db_table': 'tblcs_curriculum',
                'unique_together': {('program', 'year_level', 'subject')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('slot', 'session_date')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('academic_year', 'class_code')},
        ),
        migrations.AlterUniqueTogether(
            name='anomalyflag',
            unique_together={('attendance_record', 'rule_code')},
        ),
    ]
